<?php

use Illuminate\Database\Seeder;
use Kopp\Models\City;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::insert([
            ['name' => 'Октябрьский', 'id_filial' => 1],
            ['name' => 'Салават', 'id_filial' => 1],
            ['name' => 'Стерлитамак', 'id_filial' => 1],
            ['name' => 'Уфа', 'id_filial' => 1],
            ['name' => 'Йошкар-Ола', 'id_filial' => 2],
            ['name' => 'Саранск', 'id_filial' => 3],
            ['name' => 'Дзержинск', 'id_filial' => 4],
            ['name' => 'Кстово', 'id_filial' => 4],
            ['name' => 'Нижний Новгород', 'id_filial' => 4],
            ['name' => 'Оренбург', 'id_filial' => 5],
            ['name' => 'Орск', 'id_filial' => 5],
            ['name' => 'Пенза', 'id_filial' => 6],
            ['name' => 'Самара', 'id_filial' => 7],
            ['name' => 'Тольятти', 'id_filial' => 7],
            ['name' => 'Саратов', 'id_filial' => 8],
            ['name' => 'Альметьевск', 'id_filial' => 9],
            ['name' => 'Казань', 'id_filial' => 9],
            ['name' => 'Набережные Челны', 'id_filial' => 9],
            ['name' => 'Нижнекамск', 'id_filial' => 9],
            ['name' => 'Воткинск', 'id_filial' => 10],
            ['name' => 'Ижевск', 'id_filial' => 10],
            ['name' => 'Димитровград', 'id_filial' => 11],
            ['name' => 'Ульяновск', 'id_filial' => 11],
            ['name' => 'Чебоксары', 'id_filial' => 12],
            ['name' => 'Ангарск', 'id_filial' => 13],
            ['name' => 'Иркутск', 'id_filial' => 13],
            ['name' => 'Ачинск', 'id_filial' => 14],
            ['name' => 'Богучаны', 'id_filial' => 14],
            ['name' => 'Дивногорск', 'id_filial' => 14],
            ['name' => 'Железногорск 1', 'id_filial' => 14],
            ['name' => 'Заозерный', 'id_filial' => 14],
            ['name' => 'Зеленогорск', 'id_filial' => 14],
            ['name' => 'Канск', 'id_filial' => 14],
            ['name' => 'Кодинск', 'id_filial' => 14],
            ['name' => 'Красноярск', 'id_filial' => 14],
            ['name' => 'Лесосибирск', 'id_filial' => 14],
            ['name' => 'Минусинск', 'id_filial' => 14],
            ['name' => 'Норильск', 'id_filial' => 14],
            ['name' => 'Ужур', 'id_filial' => 14],
            ['name' => 'Шарыпово', 'id_filial' => 14],
            ['name' => 'Абакан', 'id_filial' => 15],
            ['name' => 'Благовещенск', 'id_filial' => 16],
            ['name' => 'Улан-Удэ', 'id_filial' => 17],
            ['name' => 'Агинское', 'id_filial' => 18],
            ['name' => 'Чита', 'id_filial' => 18],
            ['name' => 'Владивосток', 'id_filial' => 19],
            ['name' => 'Якутск', 'id_filial' => 20],
            ['name' => 'Хабаровск', 'id_filial' => 21],
            ['name' => 'Архангельск', 'id_filial' => 22],
            ['name' => 'Вологда', 'id_filial' => 23],
            ['name' => 'Череповец', 'id_filial' => 23],
            ['name' => 'Калининград', 'id_filial' => 24],
            ['name' => 'Советск', 'id_filial' => 24],
            ['name' => 'Черняховск', 'id_filial' => 24],
            ['name' => 'Петрозаводск', 'id_filial' => 25],
            ['name' => 'Сыктывкар', 'id_filial' => 26],
            ['name' => 'Ухта', 'id_filial' => 26],
            ['name' => 'Гатчина', 'id_filial' => 27],
            ['name' => 'Ковдор', 'id_filial' => 28],
            ['name' => 'Мончегорск', 'id_filial' => 28],
            ['name' => 'Мурманск', 'id_filial' => 28],
            ['name' => 'Полярные зори', 'id_filial' => 28],
            ['name' => 'Боровичи', 'id_filial' => 29],
            ['name' => 'Великий Новгород', 'id_filial' => 29],
            ['name' => 'Великие Луки', 'id_filial' => 30],
            ['name' => 'Псков', 'id_filial' => 30],
            ['name' => 'Санкт-Петербург', 'id_filial' => 31],
            ['name' => 'Барабинск', 'id_filial' => 32],
            ['name' => 'Бердск', 'id_filial' => 32],
            ['name' => 'Карасук', 'id_filial' => 32],
            ['name' => 'Новосибирск', 'id_filial' => 32],
            ['name' => 'Черепаново', 'id_filial' => 32],
            ['name' => 'Омск', 'id_filial' => 33],
            ['name' => 'Ишим', 'id_filial' => 34],
            ['name' => 'Тюмень', 'id_filial' => 34],
            ['name' => 'Сургут', 'id_filial' => 35],
            ['name' => 'Голицыно', 'id_filial' => 36],
            ['name' => 'Дубна', 'id_filial' => 36],
            ['name' => 'Жуковский', 'id_filial' => 36],
            ['name' => 'Зеленоград', 'id_filial' => 36],
            ['name' => 'Королев', 'id_filial' => 36],
            ['name' => 'Красногорск', 'id_filial' => 36],
            ['name' => 'Ленинский р-н, сельское поселение с/з им. Ленина', 'id_filial' => 36],
            ['name' => 'Москва', 'id_filial' => 36],
            ['name' => 'Мытищи', 'id_filial' => 36],
            ['name' => 'Одинцово', 'id_filial' => 36],
            ['name' => 'Орехово-Зуево', 'id_filial' => 36],
            ['name' => 'п. Дорохово', 'id_filial' => 36],
            ['name' => 'Подольск', 'id_filial' => 36],
            ['name' => 'Сергиев Посад', 'id_filial' => 36],
            ['name' => 'Серпухов', 'id_filial' => 36],
            ['name' => 'Химки', 'id_filial' => 36],
            ['name' => 'Барнаул', 'id_filial' => 37],
            ['name' => 'Бийск', 'id_filial' => 37],
            ['name' => 'Новоалтайск', 'id_filial' => 37],
            ['name' => 'Рубцовск', 'id_filial' => 37],
            ['name' => 'Анжеро-Судженск', 'id_filial' => 38],
            ['name' => 'Белово', 'id_filial' => 38],
            ['name' => 'Березовский', 'id_filial' => 38],
            ['name' => 'Кемерово', 'id_filial' => 38],
            ['name' => 'Ленинск-Кузнецкий', 'id_filial' => 38],
            ['name' => 'Междуреченск', 'id_filial' => 38],
            ['name' => 'Новокузнецк', 'id_filial' => 38],
            ['name' => 'Прокопьевск', 'id_filial' => 38],
            ['name' => 'Тайга', 'id_filial' => 38],
            ['name' => 'Топки', 'id_filial' => 38],
            ['name' => 'Юрга', 'id_filial' => 38],
            ['name' => 'Асино', 'id_filial' => 39],
            ['name' => 'Северск', 'id_filial' => 39],
            ['name' => 'Томск', 'id_filial' => 39],
            ['name' => 'Курган', 'id_filial' => 40],
            ['name' => 'Березники', 'id_filial' => 41],
            ['name' => 'Лысьва', 'id_filial' => 41],
            ['name' => 'Пермь', 'id_filial' => 41],
            ['name' => 'Чайковский', 'id_filial' => 41],
            ['name' => 'Екатеринбург', 'id_filial' => 42],
            ['name' => 'Заречный', 'id_filial' => 42],
            ['name' => 'Краснотурьинск', 'id_filial' => 42],
            ['name' => 'Лесной', 'id_filial' => 42],
            ['name' => 'Нижний Тагил', 'id_filial' => 42],
            ['name' => 'Новоуральск', 'id_filial' => 42],
            ['name' => 'Первоуральск', 'id_filial' => 42],
            ['name' => 'Североуральск', 'id_filial' => 42],
            ['name' => 'Серов', 'id_filial' => 42],
            ['name' => 'Магнитогорск', 'id_filial' => 43],
            ['name' => 'Миасс', 'id_filial' => 43],
            ['name' => 'Озерск', 'id_filial' => 43],
            ['name' => 'Троицк', 'id_filial' => 43],
            ['name' => 'Челябинск', 'id_filial' => 43],
            ['name' => 'Южноуральск', 'id_filial' => 43],
            ['name' => 'Белгород', 'id_filial' => 44],
            ['name' => 'Старый Оскол', 'id_filial' => 44],
            ['name' => 'Брянск', 'id_filial' => 45],
            ['name' => 'Владимир', 'id_filial' => 46],
            ['name' => 'Ковров', 'id_filial' => 46],
            ['name' => 'Воронеж', 'id_filial' => 47],
            ['name' => 'Иваново', 'id_filial' => 48],
            ['name' => 'Шуя', 'id_filial' => 48],
            ['name' => 'Калуга', 'id_filial' => 49],
            ['name' => 'Обнинск', 'id_filial' => 49],
            ['name' => 'Кострома', 'id_filial' => 50],
            ['name' => 'Железногорск 2', 'id_filial' => 51],
            ['name' => 'Курск', 'id_filial' => 51],
            ['name' => 'Курчатов', 'id_filial' => 51],
            ['name' => 'Елец', 'id_filial' => 52],
            ['name' => 'Липецк', 'id_filial' => 52],
            ['name' => 'Орел', 'id_filial' => 53],
            ['name' => 'Рязань', 'id_filial' => 54],
            ['name' => 'Вязьма', 'id_filial' => 55],
            ['name' => 'д. Мушковичи', 'id_filial' => 55],
            ['name' => 'д. Суетово', 'id_filial' => 55],
            ['name' => 'Рославль', 'id_filial' => 55],
            ['name' => 'Сафоново', 'id_filial' => 55],
            ['name' => 'Смоленск', 'id_filial' => 55],
            ['name' => 'Ярцево', 'id_filial' => 55],
            ['name' => 'Конаково', 'id_filial' => 56],
            ['name' => 'Ржев', 'id_filial' => 56],
            ['name' => 'Тверь', 'id_filial' => 56],
            ['name' => 'Торопец', 'id_filial' => 56],
            ['name' => 'Удомля', 'id_filial' => 56],
            ['name' => 'Новомосковск', 'id_filial' => 57],
            ['name' => 'Тула', 'id_filial' => 57],
            ['name' => 'Рыбинск', 'id_filial' => 58],
            ['name' => 'Ярославль', 'id_filial' => 58],
            ['name' => 'Астрахань', 'id_filial' => 59],
            ['name' => 'Волгоград', 'id_filial' => 60],
            ['name' => 'Волжский', 'id_filial' => 60],
            ['name' => 'Анапа', 'id_filial' => 61],
            ['name' => 'Армавир', 'id_filial' => 61],
            ['name' => 'Геленджик', 'id_filial' => 61],
            ['name' => 'Ейск', 'id_filial' => 61],
            ['name' => 'Краснодар', 'id_filial' => 61],
            ['name' => 'Новороссийск', 'id_filial' => 61],
            ['name' => 'Сочи', 'id_filial' => 61],
            ['name' => 'Туапсе', 'id_filial' => 61],
            ['name' => 'Волгодонск', 'id_filial' => 62],
            ['name' => 'Новочеркасск', 'id_filial' => 62],
            ['name' => 'Ростов-на-Дону', 'id_filial' => 62],
            ['name' => 'Таганрог', 'id_filial' => 62],
            ['name' => 'Пятигорск', 'id_filial' => 63],
            ['name' => 'Ставрополь', 'id_filial' => 63],
            ['name' => 'Афины', 'id_filial' => 64],
            ['name' => 'Лондон', 'id_filial' => 65],
        ]);
    }
}
